<?php
// THIS FILE IS AUTO-GENERATED BY install.php
// DO NOT EDIT MANUALLY UNLESS YOU KNOW WHAT YOU ARE DOING

// DATABASE CONNECTION
define('DB_HOST', '127.0.0.1');
define('DB_USER', 'root');
define('DB_PASS', 'root');
define('DB_NAME', 'quick_edit_db');

// GLOBAL SITE SETTINGS
define('CURRENCY_SYMBOL', '₹');

// --- DATABASE CONNECTION OBJECT ---
try {
    $conn = new PDO('mysql:host=' . DB_HOST . ';dbname=' . DB_NAME, DB_USER, DB_PASS);
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $conn->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
} catch (PDOException $e) {
    die('<h1>Database Connection Failed</h1><p>The application could not connect to the database. Please check credentials in <strong>common/config.php</strong> or run <strong>install.php</strong> again.</p><p><strong>Error:</strong> ' . $e->getMessage() . '</p>');
}

// --- HELPER FUNCTIONS ---
function format_inr($amount) {
    if (!is_numeric($amount)) { $amount = 0; }
    return CURRENCY_SYMBOL . number_format($amount, 2);
}
?>